[package]
name = "rust_web_service_iron"
version = "0.2.0"
authors = ["x1- <viva008@gmail.com>"]

[[bin]]
name = "main"
path = "src/main.rs"

[dependencies]
mime = "*"
rustc-serialize = "*"

[dependencies.iron]
version = "*"